import Container from "@/components/Container";
import PlanTabs from "@/components/myPlan/PlanTabs";
// import Saved from "@/components/myPlan/Saved";
// import TodaysPlan from "@/components/myPlan/TodaysPlan";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "FITLOG | MY PLAN",
  description: "Generated by create next app",
};

function pages() {
  return (
    <>
      <Container>
        <div className="mx-6 mt-32">
          <h1 className="uppercase font-primary font-bold text-[30px] leading-9 tracking-[-0.75px] mb-2">
            my plan
          </h1>
          <p className="font-secondary font-normal text-[14px] leading-5 text-subTitle mb-6">
            Cap of five lifts for today. Finish them, then load more.
          </p>
          <div className="px-6 pt-8 pb-6 rounded-2xl grid grid-cols-3 items-center bg-[#13161D] divide-x divide-[#232732]/60 mb-8 border border-[#232732]">
            <div className="px-8 first:pl-0">
              <p className="font-secondary font-normal text-[12px] leading-4 text-subTitle capitalize mb-1">
                exercises
              </p>
              <h1 className="font-primary font-bold text-[36px] leading-10 text-brand">
                2
              </h1>
            </div>
            <div className="px-8 first:pl-0">
              <p className="font-secondary font-normal text-[12px] leading-4 text-subTitle capitalize mb-1">
                minutes
              </p>
              <h1 className="font-primary font-bold text-[36px] leading-10 text-title">
                23
              </h1>
            </div>
            <div className="px-8 first:pl-0">
              <p className="font-secondary font-normal text-[12px] leading-4 text-subTitle capitalize mb-1">
                calories
              </p>
              <h1 className="font-primary font-bold text-[36px] leading-10 text-title">
                190
              </h1>
            </div>
          </div>
          {/* <div className="bg-[#151921] border border-[#232732] rounded-xl inline-flex items-center gap-0.5 px-1 py-1.25 mb-6">
            <p className="font-secondary font-normal text-[12px] leading-4 text-[#8A92A0] capitalize px-4 py-1.5 rounded-lg cursor-pointer">
              today's plan
            </p>
            <p className="font-secondary font-bold text-[12px] leading-4 text-title capitalize px-9 py-1.75 bg-[#1F242D] border border-[#2B303D] rounded-lg cursor-pointer">
              saved
            </p>
          </div> */}
          {/* <TodaysPlan/>
          <Saved /> */}
          <PlanTabs/>
        </div>
      </Container>
    </>
  );
}

export default pages;
